version: '3.8'

services:
  tts-api:
    build: .
    container_name: gemini-tts-api
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AUDIO_OUTPUT_DIR=/app/audio_output
    volumes:
      # Mount a local directory to save audio files
      - ./audio_output:/app/audio_output
    restart: unless-stopped
